[tool.poetry]
name = "mxfold2"
version = "0.1.1"
description = "RNA secondary structure prediction using deep neural networks with thermodynamic integrations"
authors = ["Kengo Sato <satoken@mail.dendai.ac.jp>"]
repository = "https://github.com/mxfold/mxfold2"
readme = "README.md"
license = "MIT"
build = "build.py"

[tool.poetry.dependencies]
python = "^3.8"
torch = "^1.8"
torchvision = "^0"
#torch = { version = "=1.12.1+cu116", source = "pytorch-cu116" }
#torchvision = { version = "=0.13.1+cu116", source = "pytorch-cu116" }
numpy = "*"
tqdm = "*"
wheel = "*"
pybind11 = "*"

[tool.poetry.dev-dependencies]
pylint = "*"
jupyter = "*"
pandas = "*"
tensorboard = "*"
torch-tb-profiler = "*"

[tool.poetry.scripts]
mxfold2 = "mxfold2.__main__:main"

# [[tool.poetry.source]]
# name = "pytorch-cu116"
# url = "https://download.pytorch.org/whl/cu116/"
# secondary = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
