[tool.poetry]
name = "mxfold2"
version = "0.1.0"
description = "RNA secondary structure prediction using deep neural networks with thermodynamic integrations"
authors = ["Kengo Sato <satoken@bio.keio.ac.jp>"]
license = "MIT"
build = "build.py"

[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.19.0"
torch = "^1.5.1"
torchvision = "^0.6.1"
tqdm = "^4.47.0"
tensorboard = "^2.2.2"
pandas = "^1.0.5"

[tool.poetry.dev-dependencies]
pylint = "^2.5.3"
jupyter = "^1.0.0"
setuptools_cpp = "^0.1.0"

[build-system]
requires = ["poetry>=0.12", "setuptools", "wheel", "setuptools-cpp"]
build-backend = "poetry.masonry.api"
